### ISSUE TITLE
Error in MySQL host env var in run command

### ISSUE THREAD

**Issue by gunr2171** [solidnerd/docker-bookstack#36]
This was originally posted on the [Docker Hub page](https://hub.docker.com/r/solidnerd/bookstack/) by acsandeep. Posting it here as well for more visibility.

The run command in the readme file for Docker 1.9 and up includes

```
-e DB_HOST=bookstack_db:3306 \
```

However, the variable only needs the name of the host, not the port. The program appends the port when running, so you end up with a

> SQLSTATE[HY000] [2002] Failed to parse address "bookstack_db:3306:3306"

**Comment by gabrielstuff** [comment]
yup same here. 

Full stack trace : 

```
L Community Server (GPL)
bookstack_1  | wait-for-db: done
bookstack_1  | Do not run Composer as root/super user! See https://getcomposer.org/root for details
bookstack_1  | > php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
bookstack_1  | > php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
bookstack_1  | Loading composer repositories with package information
bookstack_1  | Installing dependencies (including require-dev) from lock file
bookstack_1  | Nothing to install or update
bookstack_1  | Generating autoload files
bookstack_1  | > Illuminate\Foundation\ComposerScripts::postInstall
bookstack_1  | > php artisan optimize
bookstack_1  | Generating optimized class loader
bookstack_1  | The compiled services file has been removed.
bookstack_1  | > php artisan cache:clear
bookstack_1  | Cache cleared successfully.
bookstack_1  | > php artisan view:clear
bookstack_1  | Compiled views cleared!
bookstack_1  | **************************************
bookstack_1  | *     Application In Production!     *
bookstack_1  | **************************************
bookstack_1  |
bookstack_1  | Command Cancelled!
bookstack_1  | [2017-06-19 18:29:24] production.ERROR: PDOException: SQLSTATE[HY000] [2002] Failed to parse address "mysql:3306:3306" in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:68
bookstack_1  | Stack trace:
bookstack_1  | #0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(68): PDO->__construct('mysql:host=mysq...', 'bookstack', 'secret', Array)
bookstack_1  | #1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=mysq...', 'bookstack', 'secret', Array)
bookstack_1  | #2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=mysq...', Array, Array)
bookstack_1  | #3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
bookstack_1  | #4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
bookstack_1  | #5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(882): call_user_func(Object(Closure))
bookstack_1  | #6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(903): Illuminate\Database\Connection->getPdo()
bookstack_1  | #7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\Database\Connection->getReadPdo()
bookstack_1  | #8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
bookstack_1  | #9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
bookstack_1  | #10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
bookstack_1  | #11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
bookstack_1  | #12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
bookstack_1  | #13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
bookstack_1  | #14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(530): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
bookstack_1  | #15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
bookstack_1  | #16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
bookstack_1  | #17 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
bookstack_1  | #18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
bookstack_1  | #19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
bookstack_1  | #20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(86): value(Object(Closure))
bookstack_1  | #21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
bookstack_1  | #22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
bookstack_1  | #23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
bookstack_1  | #24 /var/www/bookstack/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #26 /var/www/bookstack/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #27 /var/www/bookstack/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #28 /var/www/bookstack/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #30 /var/www/bookstack/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #31 {main}
bookstack_1  |
bookstack_1  | [2017-06-19 18:29:24] production.ERROR: PDOException: SQLSTATE[HY000] [2002] Failed to parse address "mysql:3306:3306" in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:68
bookstack_1  | Stack trace:
bookstack_1  | #0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(68): PDO->__construct('mysql:host=mysq...', 'bookstack', 'secret', Array)
bookstack_1  | #1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=mysq...', 'bookstack', 'secret', Array)
bookstack_1  | #2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=mysq...', Array, Array)
bookstack_1  | #3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
bookstack_1  | #4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
bookstack_1  | #5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(882): call_user_func(Object(Closure))
bookstack_1  | #6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(903): Illuminate\Database\Connection->getPdo()
bookstack_1  | #7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\Database\Connection->getReadPdo()
bookstack_1  | #8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
bookstack_1  | #9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
bookstack_1  | #10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
bookstack_1  | #11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
bookstack_1  | #12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
bookstack_1  | #13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
bookstack_1  | #14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(530): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
bookstack_1  | #15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
bookstack_1  | #16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
bookstack_1  | #17 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
bookstack_1  | #18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
bookstack_1  | #19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
bookstack_1  | #20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(86): value(Object(Closure))
bookstack_1  | #21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
bookstack_1  | #22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
bookstack_1  | #23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
bookstack_1  | #24 /var/www/bookstack/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #26 /var/www/bookstack/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #27 /var/www/bookstack/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #28 /var/www/bookstack/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #30 /var/www/bookstack/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #31 {main}
bookstack_1  |
bookstack_1  | Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] Failed to parse address "mysql:3306:3306" (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations) in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
bookstack_1  | Stack trace:
bookstack_1  | #0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
bookstack_1  | #1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
bookstack_1  | #2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
bookstack_1  | #3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
bookstack_1  | #4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(530): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
bookstack_1  | #5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
bookstack_1  | #6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
bookstack_1  | #7 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
bookstack_1  | #8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
bookstack_1  | #9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
bookstack_1  | #10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(86): value(Object(Closure))
bookstack_1  | #11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
bookstack_1  | #12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
bookstack_1  | #13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
bookstack_1  | #14 /var/www/bookstack/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
bookstack_1  | #16 /var/www/bookstack/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #17 /var/www/bookstack/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #18 /var/www/bookstack/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #20 /var/www/bookstack/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
bookstack_1  | #21 {main}
bookstack_1  |
bookstack_1  |
bookstack_1  |
bookstack_1  |   [Illuminate\Database\QueryException]
bookstack_1  |   SQLSTATE[HY000] [2002] Failed to parse address "mysql:3306:3306" (SQL: sele
bookstack_1  |   ct * from information_schema.tables where table_schema = bookstack and tabl
bookstack_1  |   e_name = migrations)
bookstack_1  |
bookstack_1  |
bookstack_1  |
bookstack_1  |   [PDOException]
bookstack_1  |   SQLSTATE[HY000] [2002] Failed to parse address "mysql:3306:3306"
bookstack_1  |
bookstack_1  |
dockerbookstack_bookstack_1 exited with code 1
```
